// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schedulers2._0.api.Data;

#nullable disable

namespace Schedulers2._0.api.Migrations
{
    [DbContext(typeof(DotnetDbContext))]
    partial class DotnetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Schedulers2._0.api.Models.JobSchedulerModel", b =>
                {
                    b.Property<int>("jobSchedulerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("jobScheduler_Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("jobSchedulerId"), 1L, 1);

                    b.Property<bool?>("active")
                        .HasColumnType("BIT")
                        .HasColumnName("is_active");

                    b.Property<int?>("createdBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("createdDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<bool?>("deleted")
                        .HasColumnType("BIT")
                        .HasColumnName("is_deleted");

                    b.Property<string>("description")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("description");

                    b.Property<string>("interval")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("interval");

                    b.Property<string>("job")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job");

                    b.Property<int>("jobId")
                        .HasColumnType("int")
                        .HasColumnName("job_Id");

                    b.Property<string>("jobName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_Name");

                    b.Property<string>("jobUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_Url");

                    b.Property<int?>("updatedBy")
                        .HasColumnType("int")
                        .HasColumnName("updated_by");

                    b.Property<DateTime?>("updatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_date");

                    b.Property<string>("version")
                        .HasColumnType("varchar(1)")
                        .HasColumnName("version");

                    b.HasKey("jobSchedulerId")
                        .HasName("pk_job_scheduler");

                    b.ToTable("job_scheduler", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
